# Generated by Django 5.1.4 on 2025-01-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suit', models.CharField(choices=[('MA', 'Major Arcana'), ('CU', 'Cups'), ('PE', 'Pentacles'), ('SW', 'Swords'), ('WA', 'Wands')], max_length=2)),
                ('number', models.CharField(max_length=2)),
                ('image', models.CharField(max_length=20)),
                ('meaning_upright', models.TextField()),
                ('meaning_reversed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('is_reversed', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot_readings.card')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_age', models.IntegerField()),
                ('user_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('question', models.TextField()),
                ('cards', models.ManyToManyField(through='tarot_readings.CardPosition', to='tarot_readings.card')),
            ],
        ),
        migrations.AddField(
            model_name='cardposition',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarot_readings.reading'),
        ),
    ]
