# Generated by Django 5.1.4 on 2025-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='interpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.CharField(choices=[('MA', 'Старшие арканы'), ('CU', 'Кубки'), ('PE', 'Пентакли'), ('SW', 'Мечи'), ('WA', 'Жезлы')], max_length=2),
        ),
        migrations.AlterField(
            model_name='reading',
            name='user_gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('non-binary', 'Небинарный'), ('prefer-not-to-say', 'Предпочитаю не указывать')], max_length=20),
        ),
    ]
