# Generated by Django 5.1.4 on 2025-01-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot_readings', '0002_reading_interpretation_alter_card_suit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='user_gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=20),
        ),
    ]
