# Generated by Django 4.2.19 on 2025-02-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarot_readings", "0003_alter_reading_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="english_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Название на английском",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название на русском"),
        ),
    ]
