# Generated by Django 4.2.19 on 2025-02-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarot_readings", "0004_card_english_name_alter_card_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
    ]
