# Generated by Django 5.1.1 on 2026-01-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarot_readings", "0005_alter_reading_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_user_id", models.BigIntegerField(unique=True)),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("user_age", models.IntegerField(blank=True, null=True)),
                ("user_gender", models.CharField(blank=True, choices=[("М", "Мужской"), ("Ж", "Женский")], max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
