# Generated by Django 5.1.1 on 2026-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarot_readings", "0006_telegram_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Основной промпт", max_length=120)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Промпт",
                "verbose_name_plural": "Промпты",
            },
        ),
    ]
