# Generated by Django 5.1.1 on 2026-01-20 15:06

from django.db import migrations


DEFAULT_TAROT_PROMPT = (
    "Ты - опытный таролог с глубокими познаниями в эзотерике и психологии. "
    "Твоя задача - интерпретировать расклад Таро, учитывая позиции карт, их "
    "прямое или перевернутое положение, и вопрос клиента. "
    "Дай подробную и содержательную интерпретацию с практическими советами."
)


def seed_prompt(apps, schema_editor):
    PromptConfig = apps.get_model("tarot_readings", "PromptConfig")
    if not PromptConfig.objects.exists():
        PromptConfig.objects.create(
            name="Основной промпт",
            content=DEFAULT_TAROT_PROMPT,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tarot_readings", "0007_prompt_config"),
    ]

    operations = [
        migrations.RunPython(seed_prompt, migrations.RunPython.noop),
    ]
