# Generated by Django 5.1.1 on 2026-02-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tarot_readings", "0008_seed_prompt_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionRetentionConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("retention_days", models.PositiveIntegerField(default=365)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Хранение истории",
                "verbose_name_plural": "Хранение истории",
            },
        ),
        migrations.CreateModel(
            name="InteractionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("web", "Web"), ("telegram", "Telegram")], max_length=20)),
                ("direction", models.CharField(choices=[("in", "Входящее"), ("out", "Исходящее"), ("system", "Системное")], max_length=10)),
                ("event_type", models.CharField(max_length=64)),
                ("user_identifier", models.CharField(blank=True, max_length=128)),
                ("content", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reading", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tarot_readings.reading")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="interactionlog",
            index=models.Index(fields=["source", "created_at"], name="tarot_readi_source_9d6c9e_idx"),
        ),
        migrations.AddIndex(
            model_name="interactionlog",
            index=models.Index(fields=["user_identifier"], name="tarot_readi_user_id_2d19f8_idx"),
        ),
    ]
