# Generated by Django 5.1.1 on 2026-02-04 12:11

from django.db import migrations


def seed_retention(apps, schema_editor):
    Retention = apps.get_model("tarot_readings", "InteractionRetentionConfig")
    if not Retention.objects.exists():
        Retention.objects.create(retention_days=365, is_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("tarot_readings", "0009_interaction_logging"),
    ]

    operations = [
        migrations.RunPython(seed_retention, migrations.RunPython.noop),
    ]
