# Generated by Django 5.1.1 on 2026-02-04 12:12

import json
from django.db import migrations


def schedule_cleanup(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = IntervalSchedule.objects.get_or_create(every=1, period="days")
    PeriodicTask.objects.get_or_create(
        name="cleanup_interaction_logs_daily",
        defaults={
            "task": "tarot_readings.tasks.cleanup_interaction_logs",
            "interval": schedule,
            "args": json.dumps([]),
            "kwargs": json.dumps({}),
            "enabled": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tarot_readings", "0010_seed_interaction_retention"),
    ]

    operations = [
        migrations.RunPython(schedule_cleanup, migrations.RunPython.noop),
    ]
