"""
Django settings for tarot_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# CSRF settings
CSRF_TRUSTED_ORIGINS = ['https://catsupremacy.ru']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'django_celery_results',
    'tarot_readings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'tarot_readings.middleware.SecurityHeadersMiddleware',
    'tarot_readings.monitoring.PerformanceMonitoringMiddleware',
]

ROOT_URLCONF = 'tarot_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tarot_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database configuration
import dj_database_url

DATABASE_URL = config('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = config('STATIC_URL', default='/static/')

# Путь, куда collectstatic будет собирать файлы
STATIC_ROOT = Path(config('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles')))

# Пути, где Django будет искать статические файлы
STATICFILES_DIRS = [
    BASE_DIR / 'tarot_cards',  # Путь к вашим картам
]

MEDIA_URL = config('MEDIA_URL', default='/media/')
MEDIA_ROOT = Path(config('MEDIA_ROOT', default=str(BASE_DIR / 'media')))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configure logging handlers based on environment
_DISABLE_FILE_LOGGING = config('DISABLE_FILE_LOGGING', default=False, cast=bool)

LOGGING_HANDLERS = {
    'console': {
        'class': 'logging.StreamHandler',
        'formatter': 'simple',
    },
}

if not _DISABLE_FILE_LOGGING:
    LOGGING_HANDLERS['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': BASE_DIR / 'logs' / 'tarot.log',
        'maxBytes': 1024*1024*15,  # 15MB
        'backupCount': 10,
        'formatter': 'verbose',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': LOGGING_HANDLERS,
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'tarot_readings': {
            'handlers': ['console'] if (_DISABLE_FILE_LOGGING or DEBUG) else ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'] if (_DISABLE_FILE_LOGGING or DEBUG) else ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'] if (_DISABLE_FILE_LOGGING or DEBUG) else ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', default=True, cast=bool)
    SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', default=True, cast=bool)
    X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='DENY')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Session security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'

# CSRF security
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Redis Configuration
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

# Cache Configuration with Redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'tarot',
        'TIMEOUT': 300,  # 5 minutes default
    }
}

# Session Configuration with Redis
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 24 hours

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery task configuration
CELERY_TASK_ROUTES = {
    'tarot_readings.tasks.interpret_reading': {'queue': 'interpretations'},
}

CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_QUEUES = {
    'default': {'exchange': 'default', 'routing_key': 'default'},
    'interpretations': {'exchange': 'interpretations', 'routing_key': 'interpretations'},
}

# Celery task limits
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50

# Sentry Configuration for Error Tracking
SENTRY_DSN = config('SENTRY_DSN', default='')

if SENTRY_DSN and not DEBUG:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style='url',
                middleware_spans=True,
                signals_spans=True,
                cache_spans=True,
            ),
            CeleryIntegration(
                monitor_beat_tasks=True,
                propagate_traces=True,
            ),
        ],
        traces_sample_rate=0.1,  # 10% of transactions for performance monitoring
        profiles_sample_rate=0.1,  # 10% for profiling
        send_default_pii=False,  # Don't send personally identifiable information
        environment=config('ENVIRONMENT', default='production'),
        release=config('APP_VERSION', default='1.0.0'),
        before_send=lambda event, hint: event if not DEBUG else None,
        attach_stacktrace=True,
        max_breadcrumbs=50,
        debug=False,
    )

# Application Monitoring Settings
MONITORING_ENABLED = config('MONITORING_ENABLED', default=not DEBUG, cast=bool)

# Performance monitoring thresholds
SLOW_REQUEST_THRESHOLD = 5.0  # seconds
SLOW_QUERY_THRESHOLD = 1.0    # seconds

# GigaChat API Configuration
# Enhanced configuration based on GigaChat API documentation
GIGACHAT_CLIENT_ID = config('GIGACHAT_CLIENT_ID', default='')
GIGACHAT_CLIENT_SECRET = config('GIGACHAT_CLIENT_SECRET', default='')
GIGACHAT_API_CREDENTIALS = config('GIGACHAT_API_CREDENTIALS', default='')  # Base64 encoded for backward compatibility
GIGACHAT_DEFAULT_MODEL = config('GIGACHAT_DEFAULT_MODEL', default='GigaChat-Max')
GIGACHAT_TIMEOUT = config('GIGACHAT_TIMEOUT', default=30, cast=int)
GIGACHAT_MAX_RETRIES = config('GIGACHAT_MAX_RETRIES', default=3, cast=int)
GIGACHAT_USE_OAUTH = config('GIGACHAT_USE_OAUTH', default=True, cast=bool)  # Prefer OAuth over static credentials
GIGACHAT_MAX_TOKENS = config('GIGACHAT_MAX_TOKENS', default=1000, cast=int)
GIGACHAT_TEMPERATURE = config('GIGACHAT_TEMPERATURE', default=0.7, cast=float)

# Model-specific settings
GIGACHAT_ENABLE_AUTO_MODEL_SELECTION = config('GIGACHAT_ENABLE_AUTO_MODEL_SELECTION', default=True, cast=bool)
GIGACHAT_AVAILABLE_MODELS = config('GIGACHAT_AVAILABLE_MODELS', default='GigaChat,GigaChat-Max,GigaChat-Pro', cast=lambda v: [s.strip() for s in v.split(',')])

# GigaChat API endpoints (from documentation)
GIGACHAT_TOKEN_URL = config('GIGACHAT_TOKEN_URL', default='https://ngw.devices.sberbank.ru:9443/api/v2/oauth')
GIGACHAT_API_BASE_URL = config('GIGACHAT_API_BASE_URL', default='https://gigachat.devices.sberbank.ru/api/v1')
GIGACHAT_SCOPE = config('GIGACHAT_SCOPE', default='GIGACHAT_API_PERS')

# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_WEBHOOK_SECRET = config('TELEGRAM_WEBHOOK_SECRET', default='')
TELEGRAM_WEBHOOK_URL = config('TELEGRAM_WEBHOOK_URL', default='')

FORCE_SCRIPT_NAME = '/tarot'
